### ISSUE TITLE
How do I install without Composer

### ISSUE THREAD

**Issue by costincca** [S1SYPHOS/php-simple-captcha#2]
PHP libraries come with Composer installation or manual. Please detail how would I install manually this package. Many thanks

**Comment by S1SYPHOS** [comment]
PHP packages come with whatever installation method their developers decide to ship.

This package is meant to be installed through Composer only. If you want to run it manually, make sure you install it's dependencies and import it's main class, that's it - may I ask why you're not using Composer?

Cheers
S1SYPHOS

**Comment by S1SYPHOS** [comment]
@costincca I see, so this was kind of a "special mission" (= edge case) - sounds like you managed to do it, congratulations :grin:
